---
title: The Acoustic Wave Equation and Solutions
format:
  html:
    other-links:
      - text: Kinsler et. al. (2000)
        href: "$FILES_BASE_URL/knowledge-base/engineering/acoustics/fundamentals-of-acoustics/files/2000_Kinsler-et-al_Fundamentals-of-Acoustics_Wiley_4th-Edition.pdf"
        icon: file-pdf
---
# Introduction

There are actually many different types of pressure fluctuations that can exist in a compressible fluid. Acoustic waves are simply one kind of pressure fluctuation. Others include *ultrasonic* or *infrasonic* waves whose frequencies extend beyond the range of human hearing, *high-intensity* waves that may elicit a pain response as opposed to an audible response, and *shock* waves generated by explosions or supersonics.

Before we begin, we should define some terminology and variables that will be used.

- $\vec r$ is the equilibrium position of a fluid element.

  $$
  \vec r=x\hat x+y\hat y+z\hat z
  $$

  Unit vectors are denoted by $\hat x$, $\hat y$, and $\hat z$ for the $x$, $y$, and $z$ directions respectively.

- $\vec{\xi}$ is the *particle displacement* of a fluid element from its equilibrium position.

  $$
  \vec{\xi}=\xi_x\hat x+\xi_y\hat y+\xi_z\hat z
  $$

- $\vec u$ is the *particle velocity* of the fluid element, defined as the time derivative of the particle displacement.

  $$
  \vec u=\frac {\partial\vec{\xi}}{\partial t}=u_x\hat x+v_y\hat y+w_z\hat z
  $$

- $\rho$ is the instantaneous density at $(x, y, z)$

- $\rho_0$ is the equilibrium density at $(x, y, z)$

- $s$ is the condensation at $(x, y, z)$, defined as

  $$
  s=\frac {\Delta\rho}{\rho_0}=\frac {\rho-\rho_0}{\rho_0}
  $$

# Specific Acoustic Impedance

The ratio between the acoustic pressure, $\textbf p$, and particle speed, $\textbf u$, in a medium is defined as the specific acoustic impedance, $\textbf z$. Since both $\textbf p$ and $\textbf u$ are complex, $\textbf z\in\mathbb{C}$.

$$
\textbf z=\frac {\textbf p}{\textbf u}
$$ {#eq-specific-acoustic-impedance-definition}

For **plane waves**, the specific acoustic impedance is

$$
\textbf z=\pm\rho_0 c
$$ {#eq-plane-wave-specific-acoustic-impedance}

The sign choice in @eq-plane-wave-specific-acoustic-impedance is dependent on whether the wave propagates in the $+x$ or $-x$ direction. Units of $\textbf z$ are the *rayl*, defined as being equivalent to $1$ Pa-s/m. Since the term $\rho_0c$ is an important property of the medium, it is called the medium's *characteristic impedance*.

::: {.callout-note title="Specific Acoustic Impedances for Different Mediums"}

Depending on the medium, values for $\textbf z$ can vary across a wide range of numbers. For example, air at atmospheric pressure and $20^{\circ}$C has a specific acoustic impedance of

$$
\textbf z=415\text{ Rayl}
$$

whereas distilled water, with its density being much higher than that of air, has a specific acoustic impedance of

$$
\textbf z=1.48\times10^6\text{ Rayl}
$$

:::

@eq-plane-wave-specific-acoustic-impedance gives a real quantity and is only valid for progressive plane waves (sinusoidal waves propagating in a direction). For standing or diverging waves, $\textbf z$ becomes a complex number.

$$
\textbf z=r+jx
$$

The real part, $r$, is the *specific acoustic resistance* and the imaginary part, $x$, is the *specific acoustic reactance* of the medium.

# Spherical Waves

Some waves are more closely related to spherical waves rather than plane waves. These kinds of waves originate from a point source and propagate uniformly in all directions. In reality, this is not always true due to different mediums offering different levels of resistance. But more often than not, spherical waves are a reasonable approximation to make in most settings.

It is natural to use spherical coordinates when describing spherical waves. The Laplacian operator becomes

$$
\nabla^2=\frac {\partial^2}{\partial r^2}+\frac 2r\frac {\partial}{\partial r}+\frac 1{r^2\sin\theta}\frac {\partial}{\partial\theta}\left(\sin\theta\frac {\partial}{\partial\theta}\right)+\frac 1{r^2\sin^2\theta}\frac {\partial^2}{\partial\phi^2}
$$ {#eq-laplacian-spherical-coordinates}

where $x=r\sin\theta\cos\phi$, $y=r\sin\theta\sin\phi$, and $z=r\cos\theta$. The angle $\theta$ is the angle between the radial vector and the $z$-axis, whereas the angle $\phi$ is the angle in the $xy$-plane between the projected radial vector (on the $xy$-plane) and the $x$-axis. Some references will swap the definition of $\theta$ and $\phi$. If we assume spherical symmetry for spherical waves, then properties like pressure should only depend on time and the radial distance from the source. Therefore, @eq-laplacian-spherical-coordinates reduces down to

$$
\nabla^2=\frac {\partial^2}{\partial r^2}+\frac 2r\frac {\partial}{\partial r}
$$

When applied to the pressure field, the wave equation is

$$
\frac {\partial^2p}{\partial r^2}+\frac 2r\frac {\partial p}{\partial r}=\frac 1{c^2}\frac {\partial^2p}{\partial t^2}
$$ {#eq-spherical-wave-equation}

The solution to @eq-spherical-wave-equation for a harmonic spherical wave is given by

$$
p=\frac 1rf_1(ct-r)+\frac 1rf_2(ct+r)=\frac {\textbf A}re^{j(\omega t-kr)}+\frac {\textbf B}re^{j(\omega t+kr)}
$$

The first and second terms resemble wave propagations radially in the outwardly and inwardly direction. Waves propagating away from the point source are called *diverging* waves, whereas those propagating towards the point source are *converging* waves. The particle velocity and velocity potentials are given by

$$
\begin{aligned}
\bm{\Phi} & =-\frac {\textbf p}{j\omega\rho_0} \\
\vec{\textbf u} & =\nabla\bm{\Phi}=\left(1-\frac j{kr}\right)\frac {\textbf p}{\rho_0c}\hat r
\end{aligned}
$$ {#eq-spherical-wave-acoustic-variables}

The physically-observed acoustic quantities can be determined by taking the real part of @eq-spherical-wave-acoustic-variables. Due to the presence of the $1-\frac j{kr}$ term above, the particle velocity is *out of phase* with the pressure $\textbf p$. Therefore, the specific acoustic impedance is no longer $\rho_0c$ like that of a plane wave, but rather

$$
\textbf z=\rho_0c\cos\theta e^{j\theta}=\frac {\rho_0krc}{\sqrt{1+k^2r^2}}e^{j\theta}=\rho_0c\left(\frac {k^2r^2}{1+k^2r^2}+\frac {jkr}{1+k^2r^2}\right)
$$ {#eq-spherical-wave-specific-acoustic-impedance}

The trigonometric values of $\theta$ can be determined by drawing a right triangle. The side opposite to $\theta$ has length $1$ and the hypotenuse is $\sqrt{1+k^2r^2}$. If we separate the exponential into real and imaginary components, we can derive the specific acoustic resistance and reactance for spherical waves.

$$
\begin{aligned}
r & =\frac {\rho_0k^2r^2c}{1+k^2r^2} \\
x & =\frac {\rho_0krc}{1+k^2r^2}
\end{aligned}
$$