---
title: "Part B: The Acoustic Wave Equation"
---

# Derivation of the Wave Equation

Consider the standard 3D coordinate system. Acoustic variables include

$$
\begin{aligned}
\rho & =\rho(\textbf x, t) \\
\mathcal P & =p(\textbf x, t) \\
\mathcal P_0 & =p_0(\textbf x, t) \\
p & =\mathcal P(\textbf r, t)-\mathcal P_0(\textbf r)=p(\textbf r, t) \\
T & =
\end{aligned}
$$

Applying Newton's second law gives for small perturbations using the linearized Euler equation

$$
\frac {\partial\textbf u}{\partial t}+\frac 1{\rho_0}\nabla p=0
$$

The $\nabla p$ term is on the acoustic pressure, defined as $\frac {\partial p}{\partial x}\textbf x+\frac {\partial p}{\partial y}\textbf y+\frac {\partial p}{\partial z}\textbf z$. Next, apply mass conservation in differential form.

$$
\frac {\partial\rho}{\partial t}+\rho_0\nabla\cdot\textbf u=0
$$

# Harmonic Solutions to the Classical Wave Equation

## Harmonic Spherical Waves

The other type of wave that can be created is the spherical wave. Unlike a plane wave, spherical waves propagate in all directions simultaneously from a point source. With these wave types, the surface of constant pressure becomes a sphere in 3D or circle in 2D centered on the source.