project:
  type: website
  output-dir: ../build/_site
  post-render: "uv run update_base_urls --mode local --output-dir ../build/_site"
  resources:
    - "**/files/**/*"
    - "**/assets/**/*"
website:
  title: Frank's Engineering Notebook
  bread-crumbs: false
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Knowledge Base
        menu:
          - text: Engineering
            href: knowledge-base/engineering/index.qmd
          - text: Mathematics
            href: knowledge-base/math/index.qmd
          - text: Software
            href: knowledge-base/software/index.qmd
      - text: Class Notes
        href: notes/index.qmd
      - text: Personal Projects
        href: projects/index.qmd
    tools:
      - icon: github
        href: https://github.com/frankzwei/engineering-notebook
  sidebar:
    - id: engineering
      style: floating
      collapse-level: 1
      contents:
        - section: Acoustics
          contents:
            - section: Fundamentals of Acoustics
              contents:
                - text: Chapter 5. Acoustic Wave Equation and Solutions
                  href: knowledge-base/engineering/acoustics/fundamentals-of-acoustics/5-acoustic-wave-equation-solutions.qmd
        - section: CFD
          contents:
            - text: Introduction to AUSM Scheme
              href: knowledge-base/engineering/cfd/ausm-flux-splitting-scheme.qmd
            - section: Finite Volume Method for CFD
              contents:
                - text: Chapter 4. The Discretization Process
                  href: knowledge-base/engineering/cfd/finite-volume-method-cfd/4-discretization-process.qmd
    - id: math
      style: floating
      collapse-level: 1
      contents:
        - section: Differential Equations
          contents:
            - section: Finite Difference Schemes and PDEs
              contents:
                - text: Chapter 1. Hyperbolic PDEs
                  href: knowledge-base/math/differential-equations/finite-difference-schemes-pdes/1-hyperbolic-pdes.qmd
        - section: Statistics
          contents:
            - text: Bayesian Inference Derivations
              href: knowledge-base/math/statistics/bayesian-inference-derivations.qmd
    - id: software
      style: floating
      collapse-level: 1
      contents:
        - section: Minecraft Modding
    - id: notes
      style: floating
      collapse-level: 1
      contents:
        - section: AE 6760
          href: notes/ae6760/index.qmd
          contents:
            - text: Introduction to Acoustics
              href: notes/ae6760/lectures/introduction-acoustics.qmd
        - section: AE 6765
          href: notes/ae6765/index.qmd
          contents:
            - text: Classical Thermodynamics
              href: notes/ae6765/lectures/classical-thermodynamics.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    html-math-method: katex
crossref:
  eq-prefix: Eq.
  fig-prefix: Fig.
  sec-prefix: Sec.