project:
  type: website
  output-dir: ../build/_site
  post-render: "uv run update_base_urls --mode local --output-dir ../build/_site"
  resources:
    - "**/files/**/*"
    - "**/assets/**/*"

website:
  title: Frank's Engineering Notebook
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    html-math-method: katex